# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dba8f002334b0b5958c45fce78033cf90471586dee026674ec0719e2cbc6217d2e7ff82b70860fa6a0002a711428e6018a90584dedfb37d4be8528e3e061cda0

test:
  secret_key_base: 0bc0716e7293b0fc4d22d37bbc3a48fbf671d5f597fc1fc4adc379976af6ec9941c5c49c024d01019aeb69518d18d9ac4d4c4b9793e12fd8265eb69a063f58c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
